config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :users, :shallow => true do
    resources :restaurants do
      member do
        get :following, :followers
      end
      resources :reviews, except: [:index, :show] #create review paths
      resources :microposts, only: [:create, :destroy]
    end
  end
  resources :relationships, only: [:create, :destroy]
  root 'static_pages#home'
  get  '/restaurants',  to: 'restaurants#index'
  get  '/about',        to: 'static_pages#about'
  get  '/contact',      to: 'static_pages#contact'
  get  '/feed',      to: 'static_pages#feed'
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    respond_to do |format|
      format.html
      format.js
    end
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
  
  def feed
    if user_signed_in?
      @feed_items = current_user.feed
    end
  end
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  Office located at Room 104
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  Contact us at contact.suburblia@gmail.com
</p>

app/views/static_pages/feed.html.erb
<div class="row fix">
  <%= render 'shared/feed' %>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="center jumbotron">
  <h1>Welcome to Suburblia</h1>

  <h2>
    The finest local restaurants and businesses
  </h2>
  
  <% if user_signed_in? %>
    <%= link_to "Create a Restaurant", new_user_restaurant_path(current_user.id), class: "btn btn-lg btn-primary" %>
  <% else %>
    <%= link_to "Sign up", "#sign_up", "data-toggle" => "modal", :class => 'btn btn-lg btn-primary' %>
  <% end %>
</div>