config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :users, :shallow => true do
    resources :restaurants do
      member do
        get :following, :followers
      end
      resources :reviews, except: [:index, :show] #create review paths
      resources :microposts, only: [:create, :destroy]
    end
  end
  resources :relationships, only: [:create, :destroy]
  root 'static_pages#home'
  get  '/restaurants',  to: 'restaurants#index'
  get  '/about',        to: 'static_pages#about'
  get  '/contact',      to: 'static_pages#contact'
  get  '/feed',      to: 'static_pages#feed'
  
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
  <h3><%= pluralize(object.errors.count, "error") %>
    prohibited this <%= object.class.to_s.underscore.humanize.downcase %>
    from being saved:</h3>
  <p>There were problems with the following fields:</p>
  <ul>
  <% object.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% provide(:title, "Feed") %>
<% if @feed_items.any? %>
  <div class="col-md-12 animated fadeInUp" id="posts">
    <h1> Feed </h1>
    <% if @feed_items.blank? %>
      <p style="text-align: center;"> No posts yet </p>
    <% else %>
      <% @feed_items.each do |feed_item| %>
        <% if feed_item.content.blank? %>
          <% next %>
        <% else %>
          <div class="panel panel-default">
            <div class="panel-heading">
              Posted <%= time_ago_in_words(feed_item.created_at) %> ago by <%= feed_item.restaurant.name %>
            </div>
            <div class="panel-body">
              <%= feed_item.content %>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
<% else %>
<div class="col-md-12 animated fadeInUp">
  <h1> There's nothing here!</h1>
  <hr>
  <p style="text-align: center">Follow some restaurants to receive updates on this page</p>
</div>  
<% end %>

app/views/shared/_stats.html.erb
<% @restaurant ||= current_user %>
<div class="stats">
  <a href="<%= followers_restaurant_path(@restaurant) %>">
    <strong id="followers" class="stat">
      <%= @restaurant.followers.count %>
    </strong>
    followers
  </a>
</div>