config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :users, :shallow => true do
    resources :restaurants do
      member do
        get :following, :followers
      end
      resources :reviews, except: [:index, :show] #create review paths
      resources :microposts, only: [:create, :destroy]
    end
  end
  resources :relationships, only: [:create, :destroy]
  root 'static_pages#home'
  get  '/restaurants',  to: 'restaurants#index'
  get  '/about',        to: 'static_pages#about'
  get  '/contact',      to: 'static_pages#contact'
  get  '/feed',      to: 'static_pages#feed'
  
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  
    
  filterrific(
    default_filter_params: { sorted_by: 'name_desc' },
    available_filters: [
      :sorted_by,
      :search_query,
      :with_category_id
    ]
  )
  
  has_many :reviews
  has_many :microposts
  #Restaurant is always the "followed", never the "follower".
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy    
                                   
  has_many :followers, through: :passive_relationships, source: :follower
  
  belongs_to :category
  belongs_to :user
  validates_presence_of :name, :city, :state
  
  geocoded_by :full_address
  after_validation :geocode
  
  mount_uploader :image, ImageUploader #for carrierwave
  
  self.per_page = 12 #for pagination
  
  def full_address
    #return full address for google maps
    [address1, address2, city, state, zipcode].join(',')
  end

  scope :search_query, lambda { |query|
    return nil  if query.blank?
  
    # condition query, parse into individual keywords
    terms = query.downcase.split(/\s+/)
  
    # replace "*" with "%" for wildcard searches,
    # append '%', remove duplicate '%'s
    terms = terms.map { |e|
      ('%'+e.gsub('*', '%') + '%').gsub(/%+/, '%')
    }
    # configure number of OR conditions for provision
    # of interpolation arguments. Adjust this if you
    # change the number of OR conditions.
    num_or_conds = 1
    where(
      terms.map { |term|
        "(LOWER(restaurants.name) LIKE ?)"
      }.join(' AND '),
      *terms.map { |e| [e] * num_or_conds }.flatten
    )
  }
scope :with_category_id, lambda { |category_ids|
  where(category_id: [*category_ids])
}

scope :sorted_by, lambda { |sort_option|
  # extract the sort direction from the param value.
  direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
  case sort_option.to_s
  when /^name_/
    order("LOWER(restaurants.name) #{ direction }")
  else
    raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
  end 
}

  def self.options_for_sorted_by
    [
      ['Name (a-z)', 'name_asc']
    ]
  end
  
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  include RestaurantHelper
  #Make sure user is logged in for important pages
  before_action :set_user, except: :create
  before_action :authenticate_user!, only: [:create, :new, :edit, :update, :destroy]
  def index
    #visitor_latitude = request.location.latitude
    #visitor_longitude = request.location.longitude
    visitor_latitude = 37.8858
    visitor_longitude = -122.1180
    
    #use geocoder to filter restaurants by proximity
    #@restaurants = Restaurant.near([visitor_latitude, visitor_longitude], 30)
    
    @filterrific = initialize_filterrific(
            Restaurant,
            params[:filterrific],
            select_options: {
              sorted_by: Restaurant.options_for_sorted_by,
              with_category_id: Category.options_for_select
            },
            persistence_id: false,
            default_filter_params: {},
            available_filters: [:sorted_by, :search_query, :with_category_id],
          ) or return      
          
    
    @restaurants = Restaurant.paginate(:page => params[:page])
    
    @hash = Gmaps4rails.build_markers(@restaurants) do |restaurant, marker|
      marker.lat restaurant.latitude
      marker.lng restaurant.longitude
      marker.infowindow restaurant.name
    end
        
    #Respond with html for page load and js for AJAX updates
    respond_to do |format|
      format.html
      format.js
    end  
    
    #this declaration at end so user sees these results
    @restaurants = @filterrific.find.page(params[:page])
    
    rescue ActiveRecord::RecordNotFound => e
      # There is an issue with the persisted param_set. Reset it.
      puts "Had to reset filterrific params: #{ e.message }"
      redirect_to(reset_filterrific_url(format: :html)) and return

  end

  def new
    @restaurant = Restaurant.new(user: @user) #create a new restaurant
  end
  
  def create
    # fill user ID with user
    @restaurant = current_user.restaurants.build(restaurant_params)
    @restaurant.save
    redirect_to @restaurant
  end
  
  def show
    @restaurant = Restaurant.find(params[:id])
    @microposts = Micropost.where(restaurant_id: @restaurant)
    @reviews = Review.where(restaurant_id: @restaurant)
    if @reviews.blank?
      @avg_rating = 0
    else
      #if there are reviews, average them
      @avg_rating = @reviews.average(:rating).round(2)
    end
    
    @hash = Gmaps4rails.build_markers(@restaurant) do |restaurant, marker|
      marker.lat restaurant.latitude
      marker.lng restaurant.longitude
      marker.infowindow restaurant.description
    end
    respond_to do |format|
      format.html
      format.js
    end      
  end
  
  def edit
    @restaurant = Restaurant.find(params[:id])
  end
  
  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    redirect_to @restaurant
  end
  
  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to root_path
  end
  
  def followers
    @title = "Followers"
    @restaurant  = Restaurant.find(params[:id])
    @users = @restaurant.followers.paginate(page: params[:page])
    render 'show_follow'
  end  
  
  private # remember to add future params here
    def set_user
      @user = current_user
    end  
    def restaurant_params
      params.require(:restaurant).permit(:name, :description, :category_id,
      :address1, :address2, :city, :state, :zipcode, :phone, :email, :image, :user_id)
    end
    
    # thwart hackers
    def is_admin?
      if !current_user.id == @restaurant.user_id
        flash[:danger] = "You are not authorized to edit or delete"
        redirect_to root_path
      end
    end
end  

app/helpers/restaurant_helper.rb
module RestaurantHelper
  def check_if_owner?(restaurant)
    return false unless current_user
    @restaurant.user_id == current_user.id
  end
end

app/views/restaurants/_follow.html.erb
<%= bootstrap_form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <%= hidden_field_tag :followed_id, @restaurant.id %>
  <%= f.submit "Follow", class: "btn btn-primary btn-success" %>
<% end %>

app/views/restaurants/_follow_form.html.erb
<div id="follow_form">
  <% if current_user.following?(@restaurant) %>
    <%= render 'restaurants/unfollow' %>
  <% else %>
    <%= render 'restaurants/follow' %>
  <% end %>
</div>

app/views/restaurants/_list.html.erb
<div id="filterrific_results", class="container">
    <%= page_entries_info @restaurants %>
<!-- Restaurant listings -->
  <div class="row fix">
	  	<% @restaurants.each do |restaurant| %>
	      <div class="col-md-4">
	        <div class="thumbnail animated fadeInUp">
  	      	<% if restaurant.image_url.present? %>
  	        	<%= link_to image_tag(restaurant.image_url(:thumb)), restaurant, class:"img-responsive"%> 
            <% else %> 
              <%= link_to image_tag("http://placehold.it/500x300"), restaurant, class:"img-responsive" %>
            <% end %>
            <div class="caption">
              <h3> <%= link_to restaurant.name, restaurant %> </h3>
  	          <% if restaurant.reviews.present? %>
  	            <p class="star-rating" data-score=<%= restaurant.reviews.average(:rating).round(2) %>> </p>
  	          <% else %>
  	           <p> No ratings </p>
  	          <% end %>
            </div>
          </div>
	     </div>
	   <% end %>
  </div>
  <div class="text-center">
    <%= will_paginate @restaurants, renderer: BootstrapPagination::Rails %>
  </div>
</div>

app/views/restaurants/_unfollow.html.erb
<%= bootstrap_form_for(current_user.active_relationships.find_by(followed_id: @restaurant.id),
             html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-primary btn-danger" %>
<% end %>

app/views/restaurants/edit.html.erb
<% provide(:title, "New Restaurant") %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @restaurant do |f| %>
      <br>
      <br>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <br>
      <br>
      <%= f.label :description %>
      <br>
      <%= f.text_area :description %>
      <br>
      <br>
      <%= f.select :category_id, Category.all.map{ |f| [f.name, f.id] } %>
      <br>
      <br>
      <div class="pull-left">
      <%= f.label :address1 %>
      <%= f.text_field :address1 %>
      </div>
      <div class="pull-right">
      <%= f.label :address2 %>
      <%= f.text_field :address2 %>
      </div>
      <br>
      <br>
      <div class="pull-left">
      <%= f.label :city %>
      <%= f.text_field :city %>
      </div>
      <div class="pull-right">
      <%= f.label :state %>
      <%= f.text_field :state %>
      </div>
      <br>
      <br>
      <%= f.label :zipcode %>
      <%= f.text_field :zipcode %>
      <br>
      <br>
      <div class="pull-left">
      <%= f.label :phone %>
      <%= f.text_field :phone %>
      </div>
      <div class="pull-right">
      <%= f.label :email %>
      <%= f.text_field :email %>
      </div>
      <br>
      <br>
      <div class="pull-Left">
      <strong>Thumbnail image</strong>
      </div> 
      <div class="pull-Left">
      <p>should be 500 x 300</p>
      </div> 
      <div class="pull-Left">
      <%= f.file_field :image %>
      </div> 
      <br>
      <br>
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/restaurants/index.html.erb
<% provide(:title, "Restaurants") %>
<!-- Page Content -->
<div class="container">
  <!-- Page Header -->
  <div class="row fix">
    <div class="col-lg-12">
      <h1 class="page-header">Restaurants
        <small>in your area</small>
      </h1>
    </div>
  </div>
  <!-- Map -->
  <div class="row">
    <div class="col-md-12 animated zoomIn">
        <div id="map" style='width: auto; height: 400px;'></div>
    </div>
  </div>
</div>

  <script type="text/javascript">
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {disableDefaultUI: true}, internal: {id: 'map'}}, function(){
      markers = handler.addMarkers(<%=raw @hash.to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
    });
  </script>


<div class="help-block"></div>

<div class="container">
  <div class="row fix">    
    <div class="col-md-12 col-md-offset-2">
      <div class="input-group">
          <%= form_for_filterrific @filterrific do |f| %>
            <div class="form-group col-xs-4">
                         
              <label for="category">Category:</label>
              <%= f.select(
                :with_category_id,
                @filterrific.select_options[:with_category_id],
                { include_blank: '- Any -' },
                { :class => 'form-control' }
              ) %>
            </div>
            <div class="form-group col-xs-4">
              <label for="sort">Sorted By:</label>
              <%= f.select(:sorted_by,
                           @filterrific.select_options[:sorted_by],
                           {},
                           { :class => 'form-control' } )%>
            </div>
            <div class="form-group col-xs-4">
              <label for="search">Search:</label>
              <%= f.text_field(
                :search_query,
                class: 'filterrific-periodically-observed form-control'
              ) %>
              <%= render_filterrific_spinner %>   
            </div>        
          <% end %>
        </div>
      </div>
  </div>
</div>

<%= render(
  partial: 'restaurants/list',
  locals: { restaurants: @restaurants }
) %>

app/views/restaurants/index.js.erb
<% js = escape_javascript(
  render(partial: 'restaurants/list', locals: { restaurants: @restaurants })
) %>
$("#filterrific_results").html("<%= js %>");

app/views/restaurants/new.html.erb
<% provide(:title, "New Restaurant") %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [@user, Restaurant.new] do |f| %>
      <br>
      <br>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <br>
      <br>
      <%= f.label :description %>
      <br>
      <%= f.text_area :description %>
      <br>
      <br>
      <%= f.select :category_id, Category.all.map{ |f| [f.name, f.id] } %>
      <br>
      <br>
      <div class="pull-left">
      <%= f.label :address1 %>
      <%= f.text_field :address1 %>
      </div>
      <div class="pull-right">
      <%= f.label :address2 %>
      <%= f.text_field :address2 %>
      </div>
      <br>
      <br>
      <div class="pull-left">
      <%= f.label :city %>
      <%= f.text_field :city %>
      </div>
      <div class="pull-right">
      <%= f.label :state %>
      <%= f.text_field :state %>
      </div>
      <br>
      <br>
      <%= f.label :zipcode %>
      <%= f.text_field :zipcode %>
      <br>
      <br>
      <div class="pull-left">
      <%= f.label :phone %>
      <%= f.text_field :phone %>
      </div>
      <div class="pull-right">
      <%= f.label :email %>
      <%= f.text_field :email %>
      </div>
      <br>
      <br>
      <div class="pull-Left">
      <strong>Thumbnail image</strong>
      </div> 
      <div class="pull-Left">
      <p>should be 500 x 300</p>
      </div> 
      <div class="pull-Left">
      <%= f.file_field :image %>
      </div> 
      <br>
      <br>
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/restaurants/show.html.erb
<% provide(:title, @restaurant.name) %>
<div class="container">
  <div class="row fix">
      <div class="col-md-7">
        <div>
          <% if @restaurant.image_url.present? %>
            <%= image_tag @restaurant.image_url %>
          <% else %>
            <%= link_to image_tag("http://placehold.it/700x400") %>
          <% end %>            
        </div>
      </div>
      <div class="col-md-5 animated zoomIn">
          <div>
            <div id="map" style='width: auto; height: 400px;'></div>
          </div>
      </div>
  </div>
      
  <script type="text/javascript">
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
      markers = handler.addMarkers(<%=raw @hash.to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
      handler.getMap().setZoom(17);
    });
  </script>

  <div class="help-block"></div>
  
  <%= render "reviews/review" %>  
  <%= render "microposts/micropost" %>
  
  <div class="row fix">
    <div class="col-md-7 col-xs-12">
      <div>
        <h1><%= @restaurant.name %> <h2 class="star-rating" data-score= <%= @avg_rating %>></h2></h1>
      </div>
      <%= link_to "Write a review", "#review", "data-toggle" => "modal", :class => 'btn btn-primary btn-primary' %>
      <a class="btn btn-primary btn-primary" id="directions">Get directions</a>
      <% if check_if_owner?(@restaurant) %>
        <%= link_to "Write a post", "#micropost", "data-toggle" => "modal", :class => 'btn btn-primary btn-primary' %>
        <%= link_to "Edit", edit_restaurant_path, class: "btn btn-primary btn-primary" %>
        <%= link_to "Delete", restaurant_path, method: :delete, data: {confirm: "Are you sure you want to delete this restaurant?"}, class: "btn btn-primary btn-danger" %>
      <% end %>
    </div>
    <div class="col-md-5 col-xs-12">
      <div class="panel panel-default">
        <div class="panel-heading">Information</div>
        <ul class="list-group">
          <li class="list-group-item"><%=@restaurant.address1%>, <%=@restaurant.city%>, <%=@restaurant.state%>. <%=@restaurant.zipcode%>.</li>
          <li class="list-group-item"><%=@restaurant.phone%></li>
          <li class="list-group-item"> <%= render 'shared/stats' %> </li>
          <li class="list-group-item"> <a class="btn btn-primary btn-primary" id="menu">View menu</a> <a class="btn btn-primary btn-primary" id="hours">View hours</a></li>
        </ul>
      </div>
    </div>
  </div>
  
  <hr>
  
  <div class="row animated fadeInUp">
    <div class="col-md-7" id="reviews">
      <h1> Reviews </h1>
      <% if @reviews.blank? %>
        <p style="text-align: center;"> No reviews yet </p>
      <% else %>
        <% @reviews.each do |review| %>
          <% if review.comment.blank? %>
            <% next %>
          <% else %>
            <div class="panel panel-default">
              <div class="panel-heading">
                <strong><%= "#{review.user.first_name} #{review.user.last_name}" %></strong> <span><div class="star-rating" data-score=<%= review.rating %>></div></span>
              </div>
              <div class="panel-body">
                <%= review.comment %>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
          
    <div class="col-md-5" id="posts">
      <h1> Posts </h1>
        <% if user_signed_in? %>
          <%= render 'follow_form' %>
          <hr>
        <% end %>
      <% if @microposts.blank? %>
        <p style="text-align: center;"> No posts yet </p>
      <% else %>
        <% @microposts.each do |micropost| %>
          <% if micropost.content.blank? %>
            <% next %>
          <% else %>
            <div class="panel panel-default">
              <div class="panel-heading">
                Posted <%= time_ago_in_words(micropost.created_at) %> ago.
              </div>
              <div class="panel-body">
                <%= micropost.content %>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>   
  </div>
</div>

<!-- switch map to directions version -->
<script type="text/javascript">
  $('#directions').on('click', function (e) {
    document.getElementById("map").id = "directions"; 
    var directionsDisplay = new google.maps.DirectionsRenderer();
    var directionsService = new google.maps.DirectionsService();
    
    function calcRoute() {
      var origin      = new google.maps.LatLng(37.8858, -122.1180);                
      var destination = new google.maps.LatLng(<%= @restaurant.latitude %>, <%= @restaurant.longitude %>);
      var request = {
          origin:      origin,
          destination: destination,
          travelMode:  google.maps.TravelMode.DRIVING
      };
      directionsService.route(request, function(response, status) {
        if (status == google.maps.DirectionsStatus.OK) {
          directionsDisplay.setDirections(response);
        }
      });
    }
    
    calcRoute();
    
    var handler = Gmaps.build('Google');
    handler.buildMap({ internal: {id: 'directions'}}, function(){
    directionsDisplay.setMap(handler.getMap());
    });
    
  })
</script>