config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :users, :shallow => true do
    resources :restaurants do
      member do
        get :following, :followers
      end
      resources :reviews, except: [:index, :show] #create review paths
      resources :microposts, only: [:create, :destroy]
    end
  end
  resources :relationships, only: [:create, :destroy]
  root 'static_pages#home'
  get  '/restaurants',  to: 'restaurants#index'
  get  '/about',        to: 'static_pages#about'
  get  '/contact',      to: 'static_pages#contact'
  get  '/feed',      to: 'static_pages#feed'
  
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    A Zak Singh Production
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="#">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_head.html.erb
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <!-- gmaps4rails js files -->
    <script src="//maps.google.com/maps/api/js?key=AIzaSyAoQTCovfWgorfnYERezcjoClgFQMV6j1A"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <%= render 'layouts/shim' %>
  </head>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Suburblia", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right" id="buttons">
        <%= render "layouts/navbuttons" %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_login_modal.html.erb
<div class="container">
  <div class="modal fade" id="login" role="dialog">
    <div class="modal-dialog">
      <%= bootstrap_form_for(resource, url: session_path(:user), remote: true) do |f| %>
      <div class="modal-content">
        <div class="modal-header" style="padding:35px 50px;">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4><span class="glyphicon glyphicon-lock"></span> Login </h4>
        </div>
        <div class="modal-body" style="padding:40px 50px;">
          <form role="form">
            <%= f.email_field :email %>
            <%= f.password_field :password %>
            <%= f.check_box :remember_me %>
            <%= f.submit value: 'Sign in', :class => "btn btn-success btn-block"  %>
          </form>
        </div>
        <div class="modal-footer">
          <p><%= render "devise/shared/links" %></p>
          <%= devise_error_messages! %>
        </div>
      </div>
      <% end %>
    </div>
  </div> 
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/_navbuttons.html.erb
<li><%= link_to "Home", root_path %></li>
<li><%= link_to "Restaurants", restaurants_path %></li>
<% if user_signed_in? %>
    <li><%= link_to "Feed", feed_path %></li>        
    <li><%= link_to "Edit profile", edit_user_registration_path %></li>
    <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
<% else %>
    <li><%= link_to "Sign in", "#login", "data-toggle" => "modal", :class => 'btn btn-small' %></li>
    <li><%= link_to "Sign up", "#sign_up", "data-toggle" => "modal", :class => 'btn btn-small' %></li>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_sign_up_modal.html.erb
<div class="container">
  <div class="modal fade" id="sign_up" role="dialog">
    <div class="modal-dialog">
      <%= bootstrap_form_for(resource, url: registration_path(resource_name), remote: true ) do |f| %>
      <div class="modal-content">
        <div class="modal-header" style="padding:35px 50px;">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4><span class="glyphicon glyphicon-lock"></span> Sign up </h4>
        </div>
        <div class="modal-body" style="padding:40px 50px;">
          <form role="form">
            <%= f.email_field :email %>
            <%= f.text_field  :first_name %>
            <%= f.text_field  :last_name %>
            <%= f.password_field :password %>
            <%= f.password_field :password_confirmation %>

            <%= f.submit value: 'Sign up', :class => "btn btn-success btn-block"  %>
          </form>
        </div>
        <div class="modal-footer">
          <p><%= render "devise/shared/links" %></p>
          <%= devise_error_messages! %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/head' %>
  <%= render 'layouts/shim' %>

  <body>
    <%= render 'layouts/header' %>
    <%= render "layouts/login_modal" %>
    <%= render "layouts/sign_up_modal" %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
    <%= debug(params) if Rails.env.development? %>
    <script>
      $('.star-rating').raty({
        path: '/assets',
        readOnly: true,
        score: function () {
          return $(this).attr('data-score')
        }
      });
    </script>
    <script>
      //hides modals on successful attempts
      $(document).ready(function() {
        $('#new_user')
        .bind('ajax:success', function(evt, data, status, xhr) {
          $("[data-dismiss=modal]").trigger({ type: "click" });
          console.log('success');
          $("#buttons").html("<%= escape_javascript(render('layouts/navbuttons')) %>");
        })
        .bind("ajax:error", function(evt, xhr, status, error) {
          console.log(xhr.responseText);
        });
      });
    </script>    
    <script>
      $(document).ready(function() {
        $('#sign_up')
        .bind('ajax:success', function(evt, data, status, xhr) {
          $("[data-dismiss=modal]").trigger({ type: "click" });
          console.log('success');
          $("#buttons").html("<%= escape_javascript(render('layouts/navbuttons')) %>");
        })
        .bind("ajax:error", function(evt, xhr, status, error) {
          console.log(xhr.responseText);
        });
      });
    </script>
  </body>


</html>